### ISSUE TITLE
Cropped display on plotly

### ISSUE THREAD

**Issue by jcohenadad** [qMRLab/t1_notebooks#1]
![screen shot 2018-09-20 at 12 19 33](https://user-images.githubusercontent.com/2482071/45832284-7e6b1800-bccf-11e8-8e0a-612299307e48.png)

**Comment by mathieuboudreau** [comment]
Hmm yes, the pixel labels duplicate the legend labels, which I need to be a bit long to be descriptive. I'll look into if there's a way to customize them.

**Comment by mathieuboudreau** [comment]
I was able to add a label that doesn't get cropped by using setting the `text` property of the data structs, however, Plotly seems to want to force an extra label containing the legend entries, which always get cropped:

![bug](https://user-images.githubusercontent.com/1421029/46107829-fdbc8800-c1b6-11e8-98f4-d3827cf0c27b.png)

This happens too in their own example: https://plot.ly/python/legend/#grouped-legend

I'll post a question in their forum to see if there's any way around this, but I'm not willing to delete my legend entries (which are set using the `name` property of the data structs) to avoid this.

**Comment by mathieuboudreau** [comment]
Posted (https://community.plot.ly/t/possible-to-hide-legend-name-from-data-tooltip/14001), will report back if/when they respond.

**Comment by mathieuboudreau** [comment]
Resolved in 62d57fd

Solution was posted on the plotly forum topic I posted above: set the 'hoverinfo' property to 'x+y+text'.

![solution](https://user-images.githubusercontent.com/1421029/46251947-66b43200-c43b-11e8-9c25-f5e00d2edc49.png)
