### ISSUE TITLE
Notebook is lacking guidance

### ISSUE THREAD

**Issue by jcohenadad** [qMRLab/t1_notebooks#3]
When starting the [notebook](https://hub.mybinder.org/user/qmrlab-t1_notebooks-49rkep6o/notebooks/ir_blog/InversionRecovery.ipynb#Data-Fitting-12), it is unclear what the user should do. It would be nice to have some guidance, with a brief intro (what this notebook is about, what to expect from it, what's the purpose, etc.), then explain where to click, how to "play" with the interface, etc.

**Comment by mathieuboudreau** [comment]
Yeah – I've thought of that. It will all need to be written in code comments, as the markdown cells are used for the blog post itself. SoS generates the HTML page automatically that way.

It won't act as a traditional Jupyter Notebook I think, as the flow between figures isn't logical (you need to read the actual blog post to follow). tbd

**Comment by mathieuboudreau** [comment]
Or, there could be a separate Jupyter Notebook that duplicates the graphs for the blog post, but the danger there is that everytime a change in code in one the dev will have to know to change it in the other.

What I designed was meant to be a blog post supported by jupyter, not the other way around. But we can discuss further – this was just a mockup for now to show to Nikola, to be refined.

**Comment by mathieuboudreau** [comment]
Resolved in 2d8f39a of this repo and [`6902135`](https://github.com/qMRLab/qmrlab.github.io/commit/6902135abcda958b9ffb077d32c8daa1986fba99) of the [website repo](https://github.com/qMRLab/qmrlab.github.io).
